sudo: required
services:
  - docker

env:
- DOCKER_FILE=15/jdk/al2/Dockerfile
- DOCKER_FILE=15/jdk/debian/Dockerfile
- DOCKER_FILE=15/jdk/alpine/Dockerfile
- DOCKER_FILE=11/jre/alpine/Dockerfile
- DOCKER_FILE=11/jdk/al2/Dockerfile
- DOCKER_FILE=11/jdk/debian/Dockerfile
- DOCKER_FILE=11/jdk/alpine/Dockerfile
- DOCKER_FILE=8/jre/alpine/Dockerfile
- DOCKER_FILE=8/jdk/al2/Dockerfile
- DOCKER_FILE=8/jdk/debian/Dockerfile
- DOCKER_FILE=8/jdk/alpine/Dockerfile

script:
  - ./bin/test-image.sh
